# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GHeight' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GHeight
  pod 'RealmSwift'
  pod 'Appodeal/Native', '~>2.1'
  pod 'Appodeal/Interstitial', '~>2.1'
  pod 'Fabric'
  pod 'Crashlytics'
  pod 'FacebookCore'
  pod 'FacebookLogin'
  pod 'Firebase/Core'
  pod 'OneSignal', '>= 2.5.2', '< 3.0'

end

target 'OneSignalNotificationServiceExtension' do
    use_frameworks!
    pod 'OneSignal', '>= 2.5.2', '< 3.0'
end
